apiVersion: v1
kind: Service
metadata:
  name: app-service
  namespace: {{ .Release.Namespace | quote }}
spec:
  selector:
    app: app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP