apiVersion: apps/v1
kind: Deployment
metadata:
  name: operator
  namespace: {{ .Release.Namespace | quote }}
spec:
  replicas: {{ .Values.operatorReplicaCount }}
  selector:
    matchLabels:
      app: operator
  template:
    metadata:
      labels:
        app: operator
    spec:
      serviceAccountName: operator-sa
      containers:
        - name: operator
          image: {{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.operatorTag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
