apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: mongodbs.mongodb.example.com
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: mongodb.example.com
  # list of versions supported by this CustomResourceDefinition
  versions:
    - name: v1
      # Each version can be enabled/disabled by Served flag.
      served: true
      # One and only one version must be marked as the storage version.
      storage: true
      schema:
        openAPIV3Schema:
           type: object
           properties:
             spec:
               type: object
               properties:
                 StatefulSet:
                   type: string
                   description: "Name of the Statefulset to watch for changes"
                 Deployment:
                   type: string
                   description: "Name of the Deployment to watch for changes"
  # either Namespaced or Cluster
  scope: Cluster
  names:
    # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: mongodbs
    # singular name to be used as an alias on the CLI and for display
    singular: mongodb
    # kind is normally the CamelCased singular type. Your resource manifests use this.
    kind: MongoDB
    # shortNames allow shorter string to match your resource on the CLI
    shortNames:
    - mdb