apiVersion: apps/v1
kind: Deployment
metadata:
  name: operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: operator
  template:
    metadata:
      labels:
        app: operator
    spec:
      serviceAccountName: operator-sa
      containers:
        - name: operator
          image: nitishpradhan/operator:appdbopr
          imagePullPolicy: Always
